import { firebaseConfig, firebaseEnabled } from './firebase-config.js';
import { defaultContent } from './default-content.js';
let data=structuredClone(defaultContent), auth,db,storage,user,fb={};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pathGet=(o,p)=>p.split('.').reduce((a,k)=>a?.[k],o);
const pathSet=(o,p,v)=>{let a=o,k=p.split('.');k.slice(0,-1).forEach(x=>a=a[x]??={});a[k.at(-1)]=v};
async function initFirebase(){if(!firebaseEnabled)return false;try{const appM=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js'),authM=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js'),fsM=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js'),stM=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js');const app=appM.initializeApp(firebaseConfig);auth=authM.getAuth(app);db=fsM.getFirestore(app);storage=stM.getStorage(app);fb={...authM,...fsM,...stM};return true}catch(e){alert('خطأ Firebase: '+e.message);return false}}
function showApp(){ $('#login').style.display='none';$('#app').style.display='block';fill(); }
async function load(){const raw=localStorage.getItem('alamalContent');if(raw){const saved=JSON.parse(raw);data={...data,...saved,hero:{...defaultContent.hero,...(saved.hero||{})},about:{...defaultContent.about,...(saved.about||{})},general:{...defaultContent.general,...(saved.general||{})},cta:{...defaultContent.cta,...(saved.cta||{})}}}if(db){const s=await fb.getDoc(fb.doc(db,'site','content'));if(s.exists()){const saved=s.data();data={...data,...saved,hero:{...defaultContent.hero,...(saved.hero||{})},about:{...defaultContent.about,...(saved.about||{})},general:{...defaultContent.general,...(saved.general||{})},cta:{...defaultContent.cta,...(saved.cta||{})}}}}
function fill(){ $$('[data-path]').forEach(e=>e.value=pathGet(data,e.dataset.path)||'');const hp=$('#heroImageAdminPreview');if(hp)hp.src=data.hero?.image||'assets/hero-products.jpg';renderLists() }
function collect(){ $$('[data-path]').forEach(e=>pathSet(data,e.dataset.path,e.value)); }
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function listHtml(type,fields){return (data[type]||[]).map((it,i)=>`<div class="repeat" data-item="${type}" data-index="${i}"><div class="grid">${fields.map(f=>`<div class="field ${f.full?'full':''}"><label>${f.label}</label>${f.area?`<textarea rows="3" data-key="${f.key}">${esc(it[f.key]||'')}</textarea>`:f.options?`<select data-key="${f.key}">${f.options.map(o=>`<option value="${esc(o.value)}" ${it[f.key]===o.value?'selected':''}>${esc(o.label)}</option>`).join('')}</select>`:`<input data-key="${f.key}" type="${f.type||'text'}" value="${esc(it[f.key]||'')}">`}${f.upload?`<input type="file" accept="image/*" data-item-upload="${type}.${i}.${f.key}">`:''}</div>`).join('')}</div><div class="row-actions"><button class="btn danger" data-remove="${type}.${i}">حذف</button></div></div>`).join('')}
function renderLists(){ const cats=[{value:'دهانات داخلية',label:'دهانات داخلية'},{value:'دهانات خارجية',label:'دهانات خارجية'},{value:'دهانات ديكورية',label:'دهانات ديكورية'}]; $('#productsList').innerHTML=listHtml('products',[{key:'name',label:'اسم الصنف'},{key:'category',label:'اختر القسم',options:cats},{key:'description',label:'وصف الصنف',area:true,full:true},{key:'color',label:'اختر لون الصنف',type:'color'},{key:'image',label:'صورة الصنف أو رابطها',upload:true}]);$('#projectsList').innerHTML=listHtml('projects',[{key:'title',label:'اسم المشروع'},{key:'subtitle',label:'وصف قصير'},{key:'image',label:'الصورة أو رابطها',upload:true,full:true}]);$('#testimonialsList').innerHTML=listHtml('testimonials',[{key:'name',label:'اسم العميل'},{key:'role',label:'الصفة'},{key:'text',label:'الرأي',area:true,full:true}]);}
function collectLists(){ $$('[data-item]').forEach(box=>{const a=data[box.dataset.item][+box.dataset.index];box.querySelectorAll('[data-key]').forEach(e=>a[e.dataset.key]=e.value)}) }
async function upload(file,path){if(!file)return '';if(!storage){return await new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}const r=fb.ref(storage,`site/${Date.now()}-${file.name}`);await fb.uploadBytes(r,file);return await fb.getDownloadURL(r)}
async function save(){collect();collectLists();$('#message').innerHTML='<div class="notice">جاري الحفظ...</div>';try{for(const el of $$('[data-upload]'))if(el.files[0])pathSet(data,el.dataset.upload,await upload(el.files[0],el.dataset.upload));for(const el of $$('[data-item-upload]'))if(el.files[0]){const [t,i,k]=el.dataset.itemUpload.split('.');data[t][+i][k]=await upload(el.files[0],el.dataset.itemUpload)}localStorage.setItem('alamalContent',JSON.stringify(data));if(db)await fb.setDoc(fb.doc(db,'site','content'),data);$('#message').innerHTML='<div class="notice ok">تم حفظ التعديلات بنجاح. افتح الموقع أو حدّث الصفحة لرؤيتها.</div>';fill()}catch(e){$('#message').innerHTML='<div class="notice">تعذر الحفظ: '+esc(e.message)+'</div>'}}
$('.tab').onclick=null;$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active');$('#pageTitle').textContent=b.textContent});
$$('[data-add]').forEach(b=>b.onclick=()=>{collectLists();const t=b.dataset.add;if(t==='products')data[t].push({name:'صنف جديد',category:'دهانات داخلية',description:'',color:'#0d64d8',image:''});if(t==='projects')data[t].push({title:'مشروع جديد',subtitle:'',image:''});if(t==='testimonials')data[t].push({name:'عميل جديد',role:'',text:''});renderLists()});
document.addEventListener('click',e=>{if(e.target.dataset.remove){collectLists();const[t,i]=e.target.dataset.remove.split('.');data[t].splice(+i,1);renderLists()}});
const heroUpload=$('#heroImageUpload'),heroUrl=$('#heroImageUrl'),heroPreview=$('#heroImageAdminPreview');
if(heroUpload&&heroPreview)heroUpload.addEventListener('change',()=>{const f=heroUpload.files?.[0];if(f)heroPreview.src=URL.createObjectURL(f)});
if(heroUrl&&heroPreview)heroUrl.addEventListener('input',()=>{if(heroUrl.value.trim())heroPreview.src=heroUrl.value.trim()});

$('#save').onclick=save;
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginStatus').textContent='جاري الدخول...';if(!firebaseEnabled){if($('#email').value.trim()!=='01071908374'||$('#password').value!=='7460077'){ $('#loginStatus').textContent='رقم الموبايل أو كلمة السر غير صحيحة'; return; }localStorage.setItem('alamalAdmin','1');await load();showApp();return}try{await fb.signInWithEmailAndPassword(auth,$('#email').value,$('#password').value)}catch(err){$('#loginStatus').textContent='تعذر الدخول: '+err.message}};
$('#logout').onclick=async()=>{if(auth)await fb.signOut(auth);localStorage.removeItem('alamalAdmin');location.reload()};
const connected=await initFirebase();$('#mode').textContent=connected?'متصل بـ Firebase — التعديلات تظهر لكل الزوار':'وضع التجربة المحلي — أضف بيانات Firebase للنشر الفعلي';$('#loginHint').textContent=connected?'سجل دخولك بحساب الأدمن في Firebase.':'استخدم رقم الموبايل وكلمة السر الخاصة بالأدمن.';
if(connected){fb.onAuthStateChanged(auth,async u=>{if(u){user=u;await load();showApp()}})}else if(localStorage.getItem('alamalAdmin')){await load();showApp()}
