import { firebaseConfig, firebaseEnabled } from './firebase-config.js';
import { defaultContent } from './default-content.js';
const merge=(a,b)=>{const o=structuredClone(a);for(const [k,v] of Object.entries(b||{}))o[k]=(v&&typeof v==='object'&&!Array.isArray(v))?merge(o[k]||{},v):v;return o};
async function getContent(){let data=defaultContent;try{const l=localStorage.getItem('alamalContent');if(l)data=merge(data,JSON.parse(l))}catch{}if(firebaseEnabled)try{const {initializeApp}=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js');const {getFirestore,doc,getDoc}=await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js');const app=initializeApp(firebaseConfig),snap=await getDoc(doc(getFirestore(app),'site','content'));if(snap.exists())data=merge(defaultContent,snap.data())}catch(e){console.warn('Firebase:',e)}return data}
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const set=(id,v,html=false)=>{const e=document.getElementById(id);if(e)e[html?'innerHTML':'textContent']=v??''};
function applyVisibility(d){const map={hero:'.hero',about:'.about-grid',categories:'.categories',featuredProducts:'#productsGrid',catalog:'.catalog',projects:'.projects',testimonials:'.testimonials',cta:'.cta, .cta-band',map:'#mapEmbed'};for(const[k,sel]of Object.entries(map))if(d.visibility?.[k]===false)document.querySelectorAll(sel).forEach(e=>e.style.display='none')}
function renderProducts(d){const arr=(d.products||[]).filter(p=>p.visible!==false);const card=p=>`<article class="product-card product reveal show" data-cat="${esc(p.categorySlug||'all')}"><div class="product-art p-img">${p.image?`<img class="product-upload" src="${esc(p.image)}" alt="${esc(p.name)}">`:`<div class="mini-can" style="--pc:linear-gradient(145deg,${esc(p.color||'#0d64d8')},#132238)"></div>`}</div><div class="product-body p-info"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p></div></article>`;
  const pg=document.getElementById('productsGrid');if(pg)pg.innerHTML=arr.filter(p=>p.featured!==false).slice(0,8).map(card).join('');
  const grid=document.getElementById('productGrid');if(grid){grid.innerHTML=arr.map(card).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');grid.querySelectorAll('[data-cat]').forEach(c=>c.style.display=b.dataset.filter==='all'||c.dataset.cat===b.dataset.filter?'':'none')})}
}
function render(d){document.documentElement.style.setProperty('--blue',d.general?.primaryColor||'#0d64d8');document.documentElement.style.setProperty('--orange',d.general?.accentColor||'#ff6b18');document.documentElement.style.setProperty('--clay',d.general?.accentColor||'#ff6b18');
 document.querySelectorAll('.brand span,#brandName,#brandNameFoot').forEach(e=>e.textContent=d.general?.siteName||'');document.querySelectorAll('.brand img').forEach(e=>{if(d.general?.logo)e.src=d.general.logo});set('heroBadge',d.hero?.badge);set('heroTitle',d.hero?.title,true);set('heroText',d.hero?.text);set('aboutTitle',d.about?.title);set('aboutText',d.about?.text);set('ctaTitle',d.cta?.title);set('ctaText',d.cta?.text);
 const acts=document.querySelectorAll('.hero .actions a');if(acts[0]){acts[0].textContent=(d.hero?.primaryText||'')+' ←';acts[0].href=d.hero?.primaryLink||'#'}if(acts[1]){acts[1].textContent=d.hero?.secondaryText||'';acts[1].href=d.hero?.secondaryLink||'#'}
 const stats=document.querySelectorAll('.hero .stat');[['stat1Value','stat1Label'],['stat2Value','stat2Label'],['stat3Value','stat3Label']].forEach((k,i)=>{if(stats[i]){stats[i].querySelector('strong').textContent=d.hero?.[k[0]]||'';stats[i].querySelector('small').textContent=d.hero?.[k[1]]||''}});
 document.querySelectorAll('[data-site="phone"],#phoneText').forEach(e=>e.textContent=d.general?.phone||'');document.querySelectorAll('[data-site="email"],#emailText').forEach(e=>e.textContent=d.general?.email||'');document.querySelectorAll('[data-site="address"],#addressText').forEach(e=>e.textContent=d.general?.address||'');
 ['navCallBtn','ctaCall'].forEach(id=>{const e=document.getElementById(id);if(e){e.href='tel:'+d.general.phone;e.textContent=d.general.phone||'اتصل الآن'}});['ctaWhats','swatchModalWhats'].forEach(id=>{const e=document.getElementById(id);if(e)e.href=d.general.whatsappUrl||('https://wa.me/'+d.general.whatsapp)});
 const footerDesc=document.querySelector('footer .footer-grid>div:first-child p');if(footerDesc)footerDesc.textContent=d.general?.footerText||'';set('footAbout',d.general?.footerText);document.querySelectorAll('footer .copy,#copyrightText').forEach(e=>e.textContent=d.general?.copyright||'');const about=document.querySelector('.about-img>img');if(about&&d.about?.image)about.src=d.about.image;
 const path=location.pathname.split('/').pop();const titleMap={'about.html':'aboutTitle','products.html':'productsTitle','catalog.html':'catalogTitle','testimonials.html':'testimonialsTitle','contact.html':'contactTitle','categories.html':'categoriesTitle'};if(titleMap[path]){const h=document.querySelector('.page-banner h1');if(h)h.textContent=d.pages?.[titleMap[path]]||h.textContent}
 renderProducts(d);
 const pr=document.getElementById('projectsGrid');if(pr)pr.innerHTML=(d.projects||[]).filter(x=>x.visible!==false).map(p=>`<div class="project reveal show"><img src="${esc(p.image||'assets/cover.jpg')}" alt="${esc(p.title)}"><div><h3>${esc(p.title)}</h3><span>${esc(p.subtitle)}</span></div></div>`).join('');
 const tg=document.getElementById('testimonialsGrid')||document.querySelector('.testimonial-grid');if(tg)tg.innerHTML=(d.testimonials||[]).filter(x=>x.visible!==false).map(t=>`<div class="quote testimonial-card reveal show"><div class="stars">★★★★★</div><p>${esc(t.text)}</p><div class="who"><div class="avatar">${esc((t.name||'ع')[0])}</div><div><strong>${esc(t.name)}</strong><br><small>${esc(t.role)}</small></div></div></div>`).join('');
 const cats=document.querySelector('.cards');if(cats&&d.categories)cats.innerHTML=d.categories.filter(x=>x.visible!==false).map(c=>`<a class="cat reveal show" href="categories.html?cat=${esc(c.slug)}"><img src="${esc(c.image)}" alt="${esc(c.name)}"><h3>${esc(c.name)}</h3><p>${esc(c.description)}</p><span class="more">عرض المنتجات <span>←</span></span></a>`).join('');
 const cg=document.querySelector('.catalog-grid');if(cg&&d.catalog)cg.innerHTML=d.catalog.filter(x=>x.visible!==false).map(c=>`<button class="swatch" type="button"><span class="swatch-color" style="background:${esc(c.color)}"></span><b>${esc(c.name)}</b><small>${esc(c.code)}</small></button>`).join('');
 const map=document.getElementById('mapEmbed');if(map&&d.general.factoryMapUrl)map.innerHTML=`<iframe src="${esc(d.general.factoryMapUrl)}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" style="width:100%;height:100%;border:0"></iframe>`;
 applyVisibility(d)
}
render(await getContent());
